### ISSUE TITLE
GPU limit about Fuyu

### ISSUE THREAD

**Issue by Math312** [kyegomez/Fuyu#12]
I run the example in V100(16GB)*4， but the log shows:

    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: [enforce fail at alloc_cpu.cpp:75] err == 0. DefaultCPUAllocator: can't allocate memory: you tried to allocate 21152713932800 bytes. Error code 12 (Cannot allocate memory)

What requirements my hardware need to meet for running the example?  

I would appreciate it if you can help me.

**Comment by kyegomez** [comment]
@Math312 Can you please provide a full stack trace so I can find the root cause
